apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: nginx-example
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-example
    spec:
      containers: 
      - image: 899488875890.dkr.ecr.us-east-2.amazonaws.com/eks_registry
        name: nginx
        ports:
        - containerPort: 80
